export const data = {
 suppliers: [
  {
    id: 1,
    name: "Tata Steel Ltd",
    status: "Approved",
    submissionDate: "2022-09-25 12:32",
    defaultcurrency: "INR",
  },
  {
    id: 2,
    name: "JSW Steel Private Ltd",
    status: "Approved",
    submissionDate: "2022-09-25 12:32",
    defaultcurrency: "INR",
  },
  {
    id: 3,
    name: "Jindal Steel & Power",
    status: "Not Approved",
    submissionDate: "2022-09-25 12:32",
    defaultcurrency: "INR",
  },
  {
    id: 4,
    name: "SAIL Corporation",
    status: "Approved",
    submissionDate: "2022-09-25 12:32",
    defaultcurrency: "INR",
  },
  {
    id: 5,
    name: "Essar Steel India",
    status: "Not Approved",
    submissionDate: "2022-09-25 12:32",
    defaultcurrency: "INR",
  },
]
,
  items: [
    //item list which is given by any vendor with all the commercial terms(properties)
    {
      id: 1,
      name: "MS Round Bar 12mm",
      properties: [
        {
          name: "Unit Price",
          supplier_id: 1,
          value: 58500,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 2,
          value: 59200,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 3,
          value: 61500,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 4,
          value: 57800,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 5,
          value: 62100,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 1,
          value: 69030,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 2,
          value: 69856,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 3,
          value: 72570,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 4,
          value: 68204,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 5,
          value: 73278,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Tensile Strength",
          supplier_id: 1,
          value: 415,
          type: "number",
          currency: null,
        },
        {
          name: "Tensile Strength",
          supplier_id: 2,
          value: 420,
          type: "number",
          currency: null,
        },
        {
          name: "Tensile Strength",
          supplier_id: 3,
          value: 410,
          type: "number",
          currency: null,
        },
        {
          name: "Tensile Strength",
          supplier_id: 4,
          value: 425,
          type: "number",
          currency: null,
        },
        {
          name: "Tensile Strength",
          supplier_id: 5,
          value: 405,
          type: "number",
          currency: null,
        },
        {
          name: "Lead Time",
          supplier_id: 1,
          value: 7,
          type: "number",
          currency: null,
        },
        {
          name: "Lead Time",
          supplier_id: 2,
          value: 10,
          type: "number",
          currency: null,
        },
        {
          name: "Lead Time",
          supplier_id: 3,
          value: 14,
          type: "number",
          currency: null,
        },
        {
          name: "Lead Time",
          supplier_id: 4,
          value: 12,
          type: "number",
          currency: null,
        },
        {
          name: "Lead Time",
          supplier_id: 5,
          value: 18,
          type: "number",
          currency: null,
        },
      ],
    },
    {
      id: 2,
      name: "Portland Cement OPC 53",
      properties: [
        {
          name: "Unit Price",
          supplier_id: 1,
          value: 385,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 2,
          value: 392,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 3,
          value: 378,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 4,
          value: 395,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 5,
          value: 375,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 1,
          value: 454.3,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 2,
          value: 462.56,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 3,
          value: 446.04,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 4,
          value: 466.1,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 5,
          value: 442.5,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Compressive Strength",
          supplier_id: 1,
          value: 55,
          type: "number",
          currency: null,
        },
        {
          name: "Compressive Strength",
          supplier_id: 2,
          value: 54,
          type: "number",
          currency: null,
        },
        {
          name: "Compressive Strength",
          supplier_id: 3,
          value: 53,
          type: "number",
          currency: null,
        },
        {
          name: "Compressive Strength",
          supplier_id: 4,
          value: 56,
          type: "number",
          currency: null,
        },
        {
          name: "Compressive Strength",
          supplier_id: 5,
          value: 53,
          type: "number",
          currency: null,
        },
        {
          name: "Brand",
          supplier_id: 1,
          value: "UltraTech",
          type: "text",
          currency: null,
        },
        {
          name: "Brand",
          supplier_id: 2,
          value: "ACC",
          type: "text",
          currency: null,
        },
        {
          name: "Brand",
          supplier_id: 3,
          value: "Ambuja",
          type: "text",
          currency: null,
        },
        {
          name: "Brand",
          supplier_id: 4,
          value: "Shree Cement",
          type: "text",
          currency: null,
        },
        {
          name: "Brand",
          supplier_id: 5,
          value: "Dalmia",
          type: "text",
          currency: null,
        },
      ],
    },
    {
      id: 3,
      name: "Electrical Copper Wire 2.5mm",
      properties: [
        {
          name: "Unit Price",
          supplier_id: 1,
          value: 285,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 2,
          value: 295,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 3,
          value: 275,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 4,
          value: 290,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 5,
          value: 280,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 1,
          value: 336.3,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 2,
          value: 348.1,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 3,
          value: 324.5,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 4,
          value: 342.2,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 5,
          value: 330.4,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Conductivity",
          supplier_id: 1,
          value: 99.9,
          type: "number",
          currency: null,
        },
        {
          name: "Conductivity",
          supplier_id: 2,
          value: 99.8,
          type: "number",
          currency: null,
        },
        {
          name: "Conductivity",
          supplier_id: 3,
          value: 99.5,
          type: "number",
          currency: null,
        },
        {
          name: "Conductivity",
          supplier_id: 4,
          value: 99.7,
          type: "number",
          currency: null,
        },
        {
          name: "Conductivity",
          supplier_id: 5,
          value: 99.4,
          type: "number",
          currency: null,
        },
        {
          name: "Insulation Type",
          supplier_id: 1,
          value: "PVC",
          type: "text",
          currency: null,
        },
        {
          name: "Insulation Type",
          supplier_id: 2,
          value: "PVC",
          type: "text",
          currency: null,
        },
        {
          name: "Insulation Type",
          supplier_id: 3,
          value: "XLPE",
          type: "text",
          currency: null,
        },
        {
          name: "Insulation Type",
          supplier_id: 4,
          value: "PVC",
          type: "text",
          currency: null,
        },
        {
          name: "Insulation Type",
          supplier_id: 5,
          value: "XLPE",
          type: "text",
          currency: null,
        },
      ],
    },
    {
      id: 4,
      name: "Plywood 18mm Marine Grade",
      properties: [
        {
          name: "Unit Price",
          supplier_id: 1,
          value: 145,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 2,
          value: 152,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 3,
          value: 138,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 4,
          value: 148,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Unit Price",
          supplier_id: 5,
          value: 142,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 1,
          value: 171.1,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 2,
          value: 179.36,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 3,
          value: 162.84,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 4,
          value: 174.64,
          type: "amount",
          currency: "INR",
        },
        {
          name: "GST Included Price",
          supplier_id: 5,
          value: 167.56,
          type: "amount",
          currency: "INR",
        },
        {
          name: "Moisture Content",
          supplier_id: 1,
          value: 8.5,
          type: "number",
          currency: null,
        },
        {
          name: "Moisture Content",
          supplier_id: 2,
          value: 9.2,
          type: "number",
          currency: null,
        },
        {
          name: "Moisture Content",
          supplier_id: 3,
          value: 8.8,
          type: "number",
          currency: null,
        },
        {
          name: "Moisture Content",
          supplier_id: 4,
          value: 8.3,
          type: "number",
          currency: null,
        },
        {
          name: "Moisture Content",
          supplier_id: 5,
          value: 9.0,
          type: "number",
          currency: null,
        },
        {
          name: "Wood Type",
          supplier_id: 1,
          value: "Gurjan",
          type: "text",
          currency: null,
        },
        {
          name: "Wood Type",
          supplier_id: 2,
          value: "Hardwood",
          type: "text",
          currency: null,
        },
        {
          name: "Wood Type",
          supplier_id: 3,
          value: "Teak",
          type: "text",
          currency: null,
        },
        {
          name: "Wood Type",
          supplier_id: 4,
          value: "Gurjan",
          type: "text",
          currency: null,
        },
        {
          name: "Wood Type",
          supplier_id: 5,
          value: "Hardwood",
          type: "text",
          currency: null,
        },
      ],
    },
  ],
  footer: {
    items: [
      {
        id: 1,
        name: "Other Charges",
        properties: [
          {
            supplier_id: 1,
            value: 100,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 2,
            value: 110,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 3,
            value: 120,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 4,
            value: 130,
            type: "number",
            currency: "INR",
          },
        ]
      },
      {
        id: 2,
        name: "GST",
        properties: [
          {
            supplier_id: 1,
            value: 50,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 2,
            value: 650,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 3,
            value: 70,
            type: "number",
            currency: "INR",
          },
          {
            supplier_id: 4,
            value: 80,
            type: "number",
            currency: "INR",
          },
        ]
      },
    ]
  },
  summaryData: [
  { title: "Invited Vendors", value: 5 },
  { title: "Participated Vendors", value: 3 },
  { title: "Potential Savings", value: "12.45%" },
  { title: "Best Vendor", value: "Globex Corp" }
  ]
};