// Backup copy created for reference
export const NFASobData = {
    "packageWiseData": [
        {
            "id": 172,
            "vendorId": 281,
            "companyName": "AGILEAPT SOLUTIONS PRIVATE LIMITED",
            "packageRank": "L1",
            "nfaId": 110,
            "nfaEventType": "RFQ",
            "nfaEventId": 476,
            "initialPrice": 104600,
            "finalPrice": 104600,
            "allocation": 60,
            "itemId": 0,
            "newVendor": null,
            "version": 1,
            "allocationOn": "package",
            "valueType": "percentage",
            "totalPrice": 62760,
            "customerId": 1
        },
        {
            "id": 173,
            "vendorId": 282,
            "companyName": "HCL TECHNOLOGIES LIMITED",
            "packageRank": "L2",
            "nfaId": 110,
            "nfaEventType": "RFQ",
            "nfaEventId": 476,
            "initialPrice": 109191.5,
            "finalPrice": 109191.5,
            "allocation": 40,
            "itemId": 0,
            "newVendor": null,
            "version": 1,
            "allocationOn": "package",
            "valueType": "percentage",
            "totalPrice": 43676.6,
            "customerId": 1
        }
    ],
    "items": [
        {
            "id": 917,
            "itemCode": "",
            "itemName": "Item 1",
            "quantity": 10,
            "targetPrice": 0,
            "uom": "number",
            "plant": "Noida",
            "itemDesc": "desc"
        },
        {
            "id": 918,
            "itemCode": "",
            "itemName": "Item 2",
            "quantity": 15,
            "targetPrice": 0,
            "uom": "Ton",
            "plant": "Delhi",
            "itemDesc": "desc"
        },
        {
            "id": 919,
            "itemCode": "",
            "itemName": "Item 3",
            "quantity": 20,
            "targetPrice": 0,
            "uom": "Unit",
            "plant": "Gurgaon",
            "itemDesc": "desc"
        }
    ]
}

export const NFAGeneralData = {
    "id": 106,
    "eventCode": "NFA/8",
    "customerId": 1,
    "nfaSubject": "NFA",
    "nfaDescription": "<p>description</p>",
    "nfaEventType": "RFQ",
    "nfaEventId": 476,
    "nfaAmount": 5006,
    "nfaBudget": 100000,
    "nfaCurrency": "INR",
    "budgetStatus": "Within Budget",
    "remarks": "",
    "createdById": 124,
    "createdByName": "Shivangi Sinha",
    "createdOn": "2025-10-09T05:35:21.1925122",
    "stage": "Under Approval",
    "version": 1,
    "category": "Project",
    "exception": null,
    "spend": null,
    "projectName": "",
    "project": null,
    "nfaSaving": 94994,
    "purchOrg": "AgileApt Solutions",
    "purchGrp": "Logistics"
}

export const NFAQuestionData = [
    {
        "id": 796,
        "questionId": 14,
        "questionDescription": "Explain the financial information about the company.",
        "attachement": false,
        "attachedFileName": "",
        "optionType": false,
        "weightage": 0,
        "mandatory": true,
        "questionRequirement": "",
        "isActive": true,
        "nfaId": 110,
        "libraryId": 11,
        "libraryEntity": "Financial Questions",
        "questionCategory": "Financial Information",
        "questionSubCategory": "",
        "questionSubcategoryId": 0,
        "questioncategoryId": 2,
        "autoCalculated": false,
        "isMultiOption": null,
        "isMultipleChoice": true,
        "version": 1,
        "answer": "ANS1",
        "ansAttachements": null,
        "questionOption": []
    },
    {
        "id": 797,
        "questionId": 16,
        "questionDescription": "Multi Option Question ",
        "attachement": false,
        "attachedFileName": "Demo Terms and Condition.docx",
        "optionType": true,
        "weightage": 0,
        "mandatory": true,
        "questionRequirement": "Please select",
        "isActive": true,
        "nfaId": 110,
        "libraryId": 11,
        "libraryEntity": "Financial Questions",
        "questionCategory": "",
        "questionSubCategory": "",
        "questionSubcategoryId": 0,
        "questioncategoryId": 0,
        "autoCalculated": false,
        "isMultiOption": null,
        "isMultipleChoice": true,
        "version": 1,
        "answer": null,
        "ansAttachements": null,
        "questionOption": [
            {
                "id": 341,
                "questionOption": "Value 1",
                "weightage": 0,
                "selectYN": "Y",
                "isActive": true,
                "isAttachment": null,
                "questionId": 16
            },
            {
                "id": 342,
                "questionOption": "Value 2",
                "weightage": 0,
                "selectYN": "Y",
                "isActive": true,
                "isAttachment": null,
                "questionId": 16
            },
            {
                "id": 343,
                "questionOption": "Value 3",
                "weightage": 0,
                "selectYN": "N",
                "isActive": true,
                "isAttachment": null,
                "questionId": 16
            },
            {
                "id": 344,
                "questionOption": "Value 4",
                "weightage": 0,
                "selectYN": "N",
                "isActive": true,
                "isAttachment": null,
                "questionId": 16
            }
        ]
    },
    {
        "id": 798,
        "questionId": 19,
        "questionDescription": "Is technically qualified?",
        "attachement": false,
        "attachedFileName": "",
        "optionType": true,
        "weightage": 0,
        "mandatory": true,
        "questionRequirement": "Please specify",
        "isActive": true,
        "nfaId": 110,
        "libraryId": 85,
        "libraryEntity": "Technical Questions",
        "questionCategory": "",
        "questionSubCategory": "",
        "questionSubcategoryId": 0,
        "questioncategoryId": 0,
        "autoCalculated": false,
        "isMultiOption": null,
        "isMultipleChoice": false,
        "version": 1,
        "answer": "ANS2",
        "ansAttachements": null,
        "questionOption": []
    },
    {
        "id": 799,
        "questionId": 25,
        "questionDescription": "Question here for testing.",
        "attachement": false,
        "attachedFileName": "",
        "optionType": false,
        "weightage": 0,
        "mandatory": true,
        "questionRequirement": "DESC",
        "isActive": true,
        "nfaId": 110,
        "libraryId": 94,
        "libraryEntity": "Company Information",
        "questionCategory": "Company Information",
        "questionSubCategory": "",
        "questionSubcategoryId": 0,
        "questioncategoryId": 1,
        "autoCalculated": false,
        "isMultiOption": null,
        "isMultipleChoice": true,
        "version": 1,
        "answer": "ANS3",
        "ansAttachements": null,
        "questionOption": []
    }
]